import unittest
import torch
import os
import subprocess
from safetensors.torch import save_file, load_file


class TestXavierTorchAOScaling(unittest.TestCase):
    input_file = "temp_input_test.safetensors"
    output_file_base = "temp_output_test"
    tensor_key = "model.layer.weight"
    original_tensor_fp32 = (
        torch.randn(16, 32, dtype=torch.float32) * 10
    )  # Multiplied to have larger values

    @classmethod
    def setUpClass(cls):
        # Save the dummy input tensor
        tensors = {cls.tensor_key: cls.original_tensor_fp32}
        save_file(tensors, cls.input_file)

    @classmethod
    def tearDownClass(cls):
        # Clean up the dummy input file
        if os.path.exists(cls.input_file):
            os.remove(cls.input_file)

    def tearDown(self):
        # Clean up any output files generated by tests
        for fp8_type in ["e4m3", "e5m2"]:
            for method_suffix in [
                "wo_aoscale",
                "wo_comfyscale",
                "dyn_aoscale",
                "dyn_comfyscale",
            ]:
                output_file = (
                    f"{self.output_file_base}_{method_suffix}_{fp8_type}.safetensors"
                )
                if os.path.exists(output_file):
                    os.remove(output_file)

    def _run_xavier_and_verify(
        self, quant_method: str, fp8_type_str: str, is_comfyscale: bool
    ):
        output_file = f"{self.output_file_base}_{quant_method.replace('torchao_fp8_', '')}_{fp8_type_str}.safetensors"

        if os.path.exists(output_file):  # Clean up from previous partial run if any
            os.remove(output_file)

        cmd = [
            "python",
            "xavier.py",
            self.input_file,
            output_file,
            "--quant_method",
            quant_method,
            "--fp8_type",
            fp8_type_str,
            "--keys_to_quantize_suffix",
            ".weight",  # Matches self.tensor_key
            "--device",
            "cpu",  # Ensure tests run on CPU
        ]

        result = subprocess.run(cmd, capture_output=True, text=True)
        # print(f"Running: {' '.join(cmd)}")
        # print(f"STDOUT: {result.stdout}")
        # print(f"STDERR: {result.stderr}")
        self.assertEqual(
            result.returncode,
            0,
            f"Xavier script failed for {quant_method} {fp8_type_str}. Error: {result.stderr}",
        )
        self.assertTrue(
            os.path.exists(output_file),
            f"Output file not created for {quant_method} {fp8_type_str}",
        )

        loaded_tensors = load_file(output_file)

        expected_fp8_dtype = (
            torch.float8_e4m3fn if fp8_type_str == "e4m3" else torch.float8_e5m2
        )

        # 1. Check quantized tensor
        self.assertIn(
            self.tensor_key, loaded_tensors, "Quantized tensor not found in output."
        )
        quantized_tensor = loaded_tensors[self.tensor_key]
        self.assertEqual(
            quantized_tensor.dtype,
            expected_fp8_dtype,
            "Quantized tensor has incorrect dtype.",
        )
        self.assertEqual(
            quantized_tensor.shape,
            self.original_tensor_fp32.shape,
            "Quantized tensor has incorrect shape.",
        )

        # 2. Check scale tensor
        scale_key = self.tensor_key.replace(".weight", ".scale_weight")
        self.assertIn(scale_key, loaded_tensors, "Scale tensor not found in output.")
        scale_tensor = loaded_tensors[scale_key]
        self.assertTrue(
            scale_tensor.is_floating_point(), "Scale tensor is not a float type."
        )
        self.assertEqual(scale_tensor.numel(), 1, "Scale tensor should be a scalar.")

        # 3. Check scaled_fp8 marker
        self.assertIn("scaled_fp8", loaded_tensors, "scaled_fp8 marker not found.")
        self.assertEqual(
            loaded_tensors["scaled_fp8"].dtype,
            expected_fp8_dtype,
            "scaled_fp8 marker has incorrect dtype.",
        )

        # 4. Dequantization check
        dequantized_tensor = quantized_tensor.to(torch.float32) * scale_tensor.to(
            torch.float32
        )

        # Tolerances might need adjustment based on FP8 type and value range
        # E4M3 has less precision, especially for larger values if not perfectly scaled.
        # E5M2 has more range but fewer mantissa bits.
        rtol = 0.15 if fp8_type_str == "e4m3" else 0.1
        atol = 0.15 if fp8_type_str == "e4m3" else 0.1

        self.assertTrue(
            torch.allclose(
                dequantized_tensor, self.original_tensor_fp32, rtol=rtol, atol=atol
            ),
            f"Dequantized tensor not close to original for {quant_method} {fp8_type_str}.\\n"
            f"Original max: {self.original_tensor_fp32.abs().max().item()}, "
            f"Dequantized max: {dequantized_tensor.abs().max().item()}\\n"
            f"Max diff: {(dequantized_tensor - self.original_tensor_fp32).abs().max().item()}",
        )

        # 5. Scale value check for comfyscale
        if is_comfyscale:
            expected_comfy_scale = torch.max(torch.abs(self.original_tensor_fp32))
            self.assertTrue(
                torch.allclose(
                    scale_tensor, expected_comfy_scale, rtol=1e-2, atol=1e-2
                ),  # Scale should be very close
                f"Comfyscale scale_tensor ({scale_tensor.item()}) not close to amax of original ({expected_comfy_scale.item()}) for {quant_method} {fp8_type_str}",
            )

        # Clean up this specific output file after successful verification to save space if many tests run
        if os.path.exists(output_file):
            os.remove(output_file)

    # Test cases for each combination
    # Weight Only - AoScale
    def test_torchao_wo_aoscale_e4m3(self):
        self._run_xavier_and_verify(
            "torchao_fp8_weight_only_aoscale", "e4m3", is_comfyscale=False
        )

    def test_torchao_wo_aoscale_e5m2(self):
        self._run_xavier_and_verify(
            "torchao_fp8_weight_only_aoscale", "e5m2", is_comfyscale=False
        )

    # Weight Only - ComfyScale
    def test_torchao_wo_comfyscale_e4m3(self):
        self._run_xavier_and_verify(
            "torchao_fp8_weight_only_comfyscale", "e4m3", is_comfyscale=True
        )

    def test_torchao_wo_comfyscale_e5m2(self):
        self._run_xavier_and_verify(
            "torchao_fp8_weight_only_comfyscale", "e5m2", is_comfyscale=True
        )

    # Dynamic Act/Weight - AoScale
    def test_torchao_dyn_aoscale_e4m3(self):
        self._run_xavier_and_verify(
            "torchao_fp8_dynamic_act_weight_aoscale", "e4m3", is_comfyscale=False
        )

    def test_torchao_dyn_aoscale_e5m2(self):
        self._run_xavier_and_verify(
            "torchao_fp8_dynamic_act_weight_aoscale", "e5m2", is_comfyscale=False
        )

    # Dynamic Act/Weight - ComfyScale
    def test_torchao_dyn_comfyscale_e4m3(self):
        self._run_xavier_and_verify(
            "torchao_fp8_dynamic_act_weight_comfyscale", "e4m3", is_comfyscale=True
        )

    def test_torchao_dyn_comfyscale_e5m2(self):
        self._run_xavier_and_verify(
            "torchao_fp8_dynamic_act_weight_comfyscale", "e5m2", is_comfyscale=True
        )


if __name__ == "__main__":
    unittest.main()
